In [1]:
import pandas as pd 
import numpy as np
import timeit

from algorithms.local_search import LocalSearch
from algorithms.iterated import Iterated
from algorithms.guided import Guided
from tools.load_data import get_all

F is: 
 [[0 0 2 0 3]
 [0 0 0 3 0]
 [2 0 0 0 0]
 [0 3 0 0 1]
 [3 0 0 1 0]]
D is: 
 [[ 0 50 50 94 50]
 [50  0 22 50 36]
 [50 22  0 44 14]
 [94 50 44  0 50]
 [50 36 14 50  0]]
None

 [1 3 4 2 0]
628
F is: 
 [[0 0 2 0 3]
 [0 0 0 3 0]
 [2 0 0 0 0]
 [0 3 0 0 1]
 [3 0 0 1 0]]
D is: 
 [[ 0 50 50 94 50]
 [50  0 22 50 36]
 [50 22  0 44 14]
 [94 50 44  0 50]
 [50 36 14 50  0]]
628
628.1
628.2
628.3
628.4
628.5
628.6
628.7
628.8
628.9

 [4 3 2 0 1]
628


In [2]:
cases = get_all()
cases[0].values()

tai100a  is loaded!
tai20a  is loaded!
tai40a  is loaded!
tai60a  is loaded!
tai80a  is loaded!


dict_values([20, array([[ 0, 85, 72,  7, 49, 46, 87, 58, 17, 68, 27, 21,  6, 67, 26, 82,
        44, 35,  3, 62],
       [85,  0,  8, 51,  1, 91, 39, 87, 72, 45, 96,  7, 87, 68, 33,  3,
        21, 90, 45, 47],
       [72,  8,  0, 25, 30, 43, 97, 33, 35, 61, 42, 36, 43,  7, 84,  6,
         0,  0, 48, 62],
       [ 7, 51, 25,  0, 59, 29, 94, 82, 29,  3,  3, 51, 67, 39, 15, 66,
        42, 23, 62, 62],
       [49,  1, 30, 59,  0, 28, 76, 66, 82, 98, 35, 15, 17, 77, 44, 26,
        76, 86, 60, 62],
       [46, 91, 43, 29, 28,  0, 62, 83, 91, 57, 62, 36,  2,  2, 43, 65,
        37, 49, 61,  5],
       [87, 39, 97, 94, 76, 62,  0, 34, 53, 96, 82, 48, 28, 31, 75,  1,
        95,  7, 92, 69],
       [58, 87, 33, 82, 66, 83, 34,  0, 62, 32, 97,  5, 39, 50, 82, 93,
        71, 35, 14, 20],
       [17, 72, 35, 29, 82, 91, 53, 62,  0, 74, 49, 50, 37, 79, 19, 51,
        70, 42, 26, 79],
       [68, 45, 61,  3, 98, 57, 96, 32, 74,  0, 98, 60, 35,  9, 96, 70,
        21, 37, 37, 67],
       [27, 9

In [5]:
for case in cases:
    algo = LocalSearch(*case.values())
    print('n = ', case['n'], ' result:')
    
    print('first-impr')
    start = timeit.default_timer()
    result = algo.run('first_improvement', dlb=True)
    end = timeit.default_timer()
    print(result)
    print(f"Cost: {algo.cost_fun}")
    print('Time spent: {:.4f} seconds\n'.format(end-start))
    
    print('best-impr')
    start = timeit.default_timer()
    result = algo.run('best_improvement', dlb=True)
    end = timeit.default_timer()
    print(result)
    print(f"Cost: {algo.cost_fun}")
    print('Time spent: {:.4f} seconds\n'.format(end-start))
    
    # print('stoch-impr')
    # start = timeit.default_timer()
    # result = algo.run('stochastic_2_opt', iters=10000)
    # end = timeit.default_timer()
    # print(result)
    # print(f"Cost: {algo.cost_fun}")
    # print('Time spent: {:.4f} seconds\n'.format(end-start))


n =  20  result:
first-impr
[15  3 17 19  1  5 10 14  0  9 18  7 12 11  4  8  6  2 13 16]
Cost: 739876
Time spent: 0.1238 seconds

best-impr
[ 3  5 19  1  6 14 16  2  4 15 10 17  9  7 18 12 11 13  0  8]
Cost: 747516
Time spent: 0.1024 seconds

n =  40  result:
first-impr
[28  0 26 33 34  7 21  5 39 38 11 16  6 25 18 35 24  4  9 10 19  2  1 17
 23 37  3 29 20 13 22 14 27  8 36 31 30 15 12 32]
Cost: 3263354
Time spent: 1.7485 seconds

best-impr
[ 1 38  0 16 31 36 18 20  3  4 14  6 32 22 37  5 23  9 12 15 17  2  8 29
 26 11  7 25 27 34 19 35 24 33 30 13 39 28 10 21]
Cost: 3250978
Time spent: 1.6081 seconds

n =  60  result:
first-impr
[37 10 28 12 53 40 24 42 31 15 56 58 41  0 48 54 13 34 57 29  5  6  4  2
 49 19 11 21 22 33 17 25 52 14 20 45 35 30 36 39 46 47 16  8 59 51 23 50
  3 26 18 27 43 44 32  1 55  7 38  9]
Cost: 7542500
Time spent: 3.9447 seconds

best-impr
[15 30 56 12 33 16 53 46 23 36  7  3 10 41  4  9 59 24 40 28  6 32 49 31
 58  2 42 29 47 44 22 20 34 50 17 13 55 57 19 37 35

KeyboardInterrupt: 