In [1]:
import pandas as pd 
import numpy as np
import timeit

from algorithms.local_search import LocalSearch
from algorithms.iterated import Iterated
from algorithms.guided import Guided
from tools.load_data import get_all

In [2]:
cases = get_all()
cases[0].values()

tai100a  is loaded!
tai20a  is loaded!
tai40a  is loaded!
tai60a  is loaded!
tai80a  is loaded!


dict_values([20, array([[ 0, 85, 72,  7, 49, 46, 87, 58, 17, 68, 27, 21,  6, 67, 26, 82,
        44, 35,  3, 62],
       [85,  0,  8, 51,  1, 91, 39, 87, 72, 45, 96,  7, 87, 68, 33,  3,
        21, 90, 45, 47],
       [72,  8,  0, 25, 30, 43, 97, 33, 35, 61, 42, 36, 43,  7, 84,  6,
         0,  0, 48, 62],
       [ 7, 51, 25,  0, 59, 29, 94, 82, 29,  3,  3, 51, 67, 39, 15, 66,
        42, 23, 62, 62],
       [49,  1, 30, 59,  0, 28, 76, 66, 82, 98, 35, 15, 17, 77, 44, 26,
        76, 86, 60, 62],
       [46, 91, 43, 29, 28,  0, 62, 83, 91, 57, 62, 36,  2,  2, 43, 65,
        37, 49, 61,  5],
       [87, 39, 97, 94, 76, 62,  0, 34, 53, 96, 82, 48, 28, 31, 75,  1,
        95,  7, 92, 69],
       [58, 87, 33, 82, 66, 83, 34,  0, 62, 32, 97,  5, 39, 50, 82, 93,
        71, 35, 14, 20],
       [17, 72, 35, 29, 82, 91, 53, 62,  0, 74, 49, 50, 37, 79, 19, 51,
        70, 42, 26, 79],
       [68, 45, 61,  3, 98, 57, 96, 32, 74,  0, 98, 60, 35,  9, 96, 70,
        21, 37, 37, 67],
       [27, 9

In [3]:
for case in cases:
    algo = LocalSearch(*case.values())
    print('n = ', case['n'], ' result:')
    
    print('first-impr')
    start = timeit.default_timer()
    result = algo.run('first_improvement', dlb=True)
    end = timeit.default_timer()
    print(result)
    print(f"Cost: {algo.cost_fun}")
    print('Time spent: {:.4f} seconds\n'.format(end-start))
    
    print('best-impr')
    start = timeit.default_timer()
    result = algo.run('best_improvement', dlb=True)
    end = timeit.default_timer()
    print(result)
    print(f"Cost: {algo.cost_fun}")
    print('Time spent: {:.4f} seconds\n'.format(end-start))
    
    print('stoch-impr')
    start = timeit.default_timer()
    result = algo.run('stochastic_2_opt', iters=10000)
    end = timeit.default_timer()
    print(result)
    print(f"Cost: {algo.cost_fun}")
    print('Time spent: {:.4f} seconds\n'.format(end-start))


n =  20  result:
first-impr
[ 6  0 11 12 17  9 15  7 10  4  8 13 19 16 14  2 18  5  3  1]
Cost: 744378
Time spent: 0.1063 seconds

best-impr
[12  3  6 11  9 16  0 18 15  1 19 10 14 17  7  2  8  5  4 13]
Cost: 730716
Time spent: 0.1725 seconds

stoch-impr
[ 5 14  4 19 13 11  8  0 15  9  7 10 17  6  3  1 18 12 16  2]
Cost: 795482
Time spent: 4.2377 seconds

n =  40  result:
first-impr
[37 20 21 10 31 28 15 27  9 32  3 13 17 16 29 30  5  6  4  7 18  8  0 26
 24 33 12 14 19 36 38 23 25 35  1 11 22 39  2 34]
Cost: 3305140
Time spent: 1.0777 seconds

best-impr
[25 11 21 28 19 32 26 27  7 13 35 37  3 16  9 33 34 38 36  0 18  8 22 10
  2 39 29 30  4 17  5 20 12 23  1 14 15 24 31  6]
Cost: 3298334
Time spent: 1.4751 seconds

stoch-impr


KeyboardInterrupt: 